apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: openshift-gitops
spec:
  destination:
    namespace: pacman
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-lifecycle/pacman
    repoURL: https://github.com/avaleror/ocp-coffee-break.git
    targetRevision: master
  syncPolicy:
    automated:
      selfHeal: true

