apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: argo-deploy-pr
  namespace: argo-deploy
  labels:
    app: argo-deploy-app 
spec:
  clusterSelector:
    matchLabels:
      deployer: argocd
